### PR TITLE
`name` is required rather than `description` #28

### PR DESCRIPTION
**Pull request by m-mohr**
Implements #28

### CODE REVIEW

**Comment by pjhartzell** [comment]
I'm good with this.

**Comment by drwelby** [comment]
@gadomski can you expand on your comments in https://github.com/stac-extensions/classification/issues/28#issuecomment-1151639912?

**Review by gadomski — COMMENTED** [review]
There's some other text in the README that should be updated to use `name`-type text: https://github.com/stac-extensions/classification/blob/abd8d3b111b453b5d909ad63aeb96bc1189b089d/README.md?plain=1#L121-L124.

**Comment by m-mohr** [comment]
Well, I mean it doesn't say what machine-readable actually means. So these are valid names so the question is more whether we want to actually define this and restrict the allowed characters in the schema for the name?

**Comment by gadomski** [comment]
> Well, I mean it doesn't say what machine-readable actually means

True, but if we don't restrict the text field in the schema, then at least the README should reflect what we _think_ it should look like?

I don't think we should restrict the `name` field, since there's no technical requirement that (e.g.) query parameters can't contain spaces. However, it might be good to provide some text suggesting best practices practices for names, maybe something like this:

> The `name` field should be picked to be short and easily understandable without domain-specific knowledge. For example, prefer "urban" instead of "urban areas". Because the `name` field could be used to filter data (for example, in a HTTP query parameter), prefer hyphens to spaces, e.g. use "deciduous-forest" instead of "deciduous forest". Avoid the use of acronyms. Use the `description` field to provide more verbose information about the class.

**Comment by m-mohr** [comment]
Some additional thoughts: I'm right now thinking about other use cases and a human-readable title like thing would also be good for legends. We could argue that the name would also be a valid use case for that. You probably don't want to use the description for legens on maps etc, right?

I'm happy to go without a regex and just adopt your proposal, too.

**Comment by drwelby** [comment]
If we want to cover more use cases we could consider making classes an object with machine readable keys and name/description in an object as done with assets.

Or perhaps we add "title" as an optional short name for legends, etc.

**Comment by drwelby** [comment]
In the Maxar ARD Python SDK we have tile objects that are abstractions of STAC Items that represents an acquisition and files generated from it. So you can do something like:

```
for tile in my_s3_storage:
    if not tile.cloud_mask.intersects(my_geometry):
       display(tile)
```
We have some accessor magic that loads the assets, but what we'd like to be able to do is extend the magic to also be able to read classes to be able to test against them too . In the case of the cloud mask, we use the classification extension to describe its two classes: clouds and cloud shadows. So we'd want the machine-readable name to be able to do:

```
    if not tile.cloud_mask.clouds.intersects(my_geometry):
```

**Comment by gadomski** [comment]
> So we'd want the machine-readable name to be able to do:
>>  if not tile.cloud_mask.clouds.intersects(my_geometry):

In this case, you need more than "machine-readable", you need "valid attribute name in Python", yes? I think this would be an argument _for_ @m-mohr's use-a-regex-to-validate-name approach, so you could `s/-/_/` to get your attribute name.

**Comment by drwelby** [comment]
We already handle making names valid in Python, we just wouldn't want someone else to get stuck having to build a similar solution that has to take a long description and make it sane to write code around.

**Pull request merged**
