### PR TITLE
Add classification:incomplete #33

### PR DESCRIPTION
**Pull request by m-mohr**
This PR is based on #32! It adds `classification:incoplete` and a recommendation to describe a range of values. See #33 for the discussion.

cc @pjhartzell @gadomski

### CODE REVIEW

**Comment by drwelby** [comment]
other synonyms to see how they look:

`classification:incomplete`
`classification:partial`
`classification:limited`

**Comment by m-mohr** [comment]
I found incomplete more intuitive and self-explanatory, but I'm a non-native speaker so may not get the nuances here.

**Comment by drwelby** [comment]
`incomplete` can also mean `unfinished` but I don't think it's a problem. I just wanted to think about other words now so I don't regret it when I think of the _perfect_ word in two months.

**Comment by pjhartzell** [comment]
The intent of `classification:incomplete` is to indicate that only a subset (e.g., multiple no-data) of the data are described in `classification:classes`?

I don't have a strong opinion on this. It's optional and doesn't break anything, so 👍 .

**Comment by m-mohr** [comment]
Yes, but it would not be really needed if we settle on ranges for classes. We need to decide for or against ranges at some point :-)

**Pull request closed without merging**
